model: yolov5x-cls.pt
data: Detect-Thalassemia-2-1
epochs: 300
batch_size: 16
imgsz: 640
nosave: false
cache: null
device: '0'
workers: 8
project: runs/train-cls
name: exp
exist_ok: false
pretrained: weights/yolov5x-cls.pt
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: runs/train-cls/exp
